name: CI

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
      uses: actions/checkout@v3

      - name: Setup Node.JS
        uses: actions/setup-node@master

      - name: Building frontend dependencies
        run: |
          npm install
          npm run build

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Setup Dependencies
        run:  composer install --ignore-platform-reqs

      - name: Setup Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Prepare Laravel Application
        run: |
          php artisan storage:link
          
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

