name: Test Workflow

on: 
    push:
        branches:
            - '*'
            - '!master'
jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions/setup-node@master
        
      - name: Setup NPM
        run: |
          npm install
          npm run build

      - name: Setup PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.2"

      - name: Setup Dependencies
        uses: "ramsey/composer-install@v2"
  
      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env          
          php artisan key:generate

      - name: Preparar .env
        uses: DamianReeves/write-file-action@master
        with:
          path: .env
          write-mode: append
          contents: |
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_DATABASE=${{ secrets.DB_DATABASE }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}

      - name: Run Testsuite
        run: vendor/bin/phpunit tests/
